# Generated by Django 3.1.2 on 2021-04-27 23:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('スターバックス', 'Starbucks'), ('成城石井', '成城石井'), ('小学校', '小学校'), ('マクドナルド', "McDonald's")], default=1, max_length=23),
            preserve_default=False,
        ),
    ]
