# Generated by Django 3.2 on 2021-05-08 01:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_score_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='comparison',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='choice',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('スターバックス', 'Starbucks'), ('成城石井', '成城石井'), ('KFC', 'KFC'), ('マクドナルド', 'マクドナルド'), ('無印良品', '無印良品'), ('スーパーマーケット', 'スーパーマーケット'), ('小学校', '小学校'), ('中学校', '中学校')], max_length=46),
        ),
    ]
