# Generated by Django 3.2 on 2021-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_auto_20210508_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='comparison',
        ),
        migrations.AddField(
            model_name='score',
            name='name_sub',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
